dist: xenial
sudo: require

language: python

python:
  - "3.7"

os:
  - linux
  
cache:
  pip: true
  directories:
  - "~/.platformio"
  
install:
  - pip install -U platformio

env:
  - TARGET=esp32 PLATFORM=arduino BT=yes AUTHENTICATION=yes FILESYSTEM=FAT
  - TARGET=esp32 PLATFORM=arduino BT=yes AUTHENTICATION=no FILESYSTEM=SPIFFS
  - TARGET=esp8266 PLATFORM=arduino BT=no AUTHENTICATION=yes FILESYSTEM=SPIFFS
  - TARGET=esp8266 PLATFORM=arduino BT=no AUTHENTICATION=no FILESYSTEM=SPIFFS
  - TARGET=all PLATFORM=PIO BT=yes AUTHENTICATION=yes

before_script:
  - platformio update
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - mv arduino-1.8.5 $HOME/arduino_ide
  - cd $HOME/arduino_ide/hardware
  - mkdir esp8266com
  - cd esp8266com
  - git clone https://github.com/esp8266/Arduino.git esp8266
  - cd esp8266
  - git submodule update --init
  - cd tools
  - python get.py
  - cd $HOME/arduino_ide/hardware
  - mkdir esp32
  - cd esp32
  - git clone https://github.com/espressif/arduino-esp32.git esp32
  - cd esp32
  - git submodule update --init
  - cd tools
  - python get.py
  - cp -r $TRAVIS_BUILD_DIR/libraries/ESP32SSDP-1.0.1 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/arduinoWebSockets-2.1.4 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/DHT_sensor_library_for_ESPx-1.0.6 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/esp8266-oled-ssd1306-4.0.0 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/TFT_eSPI-1.4.11 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/lv_arduino-2.0.3 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/ESP8266-Arduino-Lua-0.0.30 $HOME/arduino_ide/libraries/
  - cp -r $TRAVIS_BUILD_DIR/libraries/SdFat-1.1.0 $HOME/arduino_ide/libraries/
  - cd $TRAVIS_BUILD_DIR
  - source command.sh
  - export PATH="$HOME/arduino_ide:$PATH"
    
script:
  - build_sketch  $TRAVIS_BUILD_DIR/esp3d/esp3d.ino $TARGET $PLATFORM $BT $AUTHENTICATION $FILESYSTEM

notifications:
  email:
    on_success: always
    on_failure: always
